[system]
# 查询网址
URL = https://jxcf.jxeea.cn

# 准考证号
EXAM_NO = 1432143

# 身份证件号码后4位
ID_CARD_LAST4 = 1234

# 浏览器是否显示
HEADLESS = False

# 屏幕截图
SCREENSHOT_DIR = screenshots

# 日志目录
LOGS_DIR = logs

# 查询间隔（单位：秒）
# 86400 = 1天
# 7200 = 2小时
interval = 10


# Chrome浏览器路径
browser_path = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe